// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjbtulFiDRucHqIFfkuJHG1xfzR2FYKRA',
    appId: '1:663462789254:web:93210f59c249bcc7e91107',
    messagingSenderId: '663462789254',
    projectId: 'ecommerceapp-67746',
    authDomain: 'ecommerceapp-67746.firebaseapp.com',
    storageBucket: 'ecommerceapp-67746.appspot.com',
    measurementId: 'G-F3FYQRNZJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1rzuimZ4XlKEoXJOEzPQJqRnenXNQ6vk',
    appId: '1:663462789254:android:4d6fc9fefa70f444e91107',
    messagingSenderId: '663462789254',
    projectId: 'ecommerceapp-67746',
    storageBucket: 'ecommerceapp-67746.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyp8bQrTL7uyBV2UYGzAHUASzOvAm7zU8',
    appId: '1:663462789254:ios:bb4172ee30c8e8a8e91107',
    messagingSenderId: '663462789254',
    projectId: 'ecommerceapp-67746',
    storageBucket: 'ecommerceapp-67746.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyp8bQrTL7uyBV2UYGzAHUASzOvAm7zU8',
    appId: '1:663462789254:ios:2c493ace176724b4e91107',
    messagingSenderId: '663462789254',
    projectId: 'ecommerceapp-67746',
    storageBucket: 'ecommerceapp-67746.appspot.com',
    iosBundleId: 'com.example.eCommerceApp.RunnerTests',
  );
}
